name: Release
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yaml'
      - 'src/**'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic_release.outputs.new_release_version }}
      published: ${{ steps.semantic_release.outputs.new_release_published }}
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Create GitHub App token
        id: create_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.create_token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run tests
        run: pytest

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./src
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}

  docker:
    name: Docker Build and Push
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.published == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/elastic-datastream-snapshots:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/elastic-datastream-snapshots:${{ needs.release.outputs.version }}